In [2]:
import pandas as pd

df_ips = pd.read_csv('../donnees/fr-en-ips_lycees.csv', sep=';')

/Users/alexis/opt/anaconda3/lib/python3.8/site-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
df_ips.head()

,Rentrée scolaire,Académie,Code du département,Département,UAI,Nom de l'établissment,Code INSEE de la commune,Nom de la commune,Secteur,Type de lycée,IPS voie GT,IPS voie PRO,IPS Ensemble GT-PRO,Ecart-type de l'IPS voie GT,Ecart-type de l'IPS voie PRO
0,2016-2017,LYON,1.0,AIN,0010010F,LYCEE GENERAL ET TECHNOLOGIQUE DU BUGEY,1034.0,BELLEY,public,LEGT,109.5,NaN,109.5,NaN,NaN
1,2016-2017,LYON,1.0,AIN,0010034G,LYCEE POLYVALENT PAUL PAINLEVE,1283.0,OYONNAX,public,LPO,92.2,73.4,86.5,NaN,NaN
2,2016-2017,LYON,1.0,AIN,0010070W,LYCEE GENERAL ET TECHNOLOGIQUE PRIVE SAINT PIERRE,1053.0,BOURG EN BRESSE,privé sous contrat,LEGT,126.5,NaN,126.5,NaN,NaN
3,2016-2017,LYON,1.0,AIN,0010075B,LYCEE GENERAL ET TECHNOLOGIQUE PRIVE SAINT JOSEPH,1249.0,MIRIBEL,privé sous contrat,LEGT,120.7,NaN,120.7,NaN,NaN
4,2016-2017,LYON,1.0,AIN,0011010T,LYCEE PROFESSIONNEL DU BUGEY,1034.0,BELLEY,public,LP,NaN,84.6,84.6,NaN,NaN

In [10]:
df_ips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21777 entries, 0 to 21776
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Rentrée scolaire              21777 non-null  object
 1   Académie                      21777 non-null  object
 2   Code du département           21687 non-null  float64
 3   Département                   21777 non-null  object
 4   UAI                           21777 non-null  object
 5   Nom de l'établissment         21777 non-null  object
 6   Code INSEE de la commune      21687 non-null  float64
 7   Nom de la commune             21777 non-null  object
 8   Secteur                       21777 non-null  object
 9   Type de lycée                 21777 non-null  object
 10  IPS voie GT                   14792 non-null  float64
 11  IPS voie PRO                  12556 non-null  float64
 12  IPS Ensemble GT-PRO           21777 non-null  float64
 13  Ecart-type de l'IPS voie GT   7411 non-null   float64
 14  Ecart-type de l'IPS voie PRO  6274 non-null   float64
dtypes: float64(7), object(8)
memory usage: 2.5+ MB

In [13]:
print(len(df_ips['Ecart-type de l\'IPS voie PRO'].isna()))

21777

In [12]:
print(len(df_ips))

21777

In [14]:
df_res = pd.read_csv('../donnees/fr-en-indicateurs-de-resultat-des-lycees-gt_v2.csv', sep=';')

In [15]:
df_res.head()

,Année,UAI,Etablissement,Secteur,Code commune,Commune,Code departement,Département,Académie,Code région,...,Valeur ajoutée du taux de mentions - S2TMD,Valeur ajoutée du taux de mentions - STHR,Nombre de mentions TB avec félicitations - G,Nombre de mentions TB sans félicitations - G,Nombre de mentions B - G,Nombre de mentions AB - G,Nombre de mentions TB avec félicitations - T,Nombre de mentions TB sans félicitations - T,Nombre de mentions B - T,Nombre de mentions AB - T
0,2025,0511135G,LYCEE NOTRE-DAME ST VICTOR,privé sous contrat,51230,EPERNAY,51,MARNE,REIMS,44,...,NaN,NaN,NaN,10.0,20.0,38.0,NaN,NaN,NaN,NaN
1,2025,0511145T,LYCEE ST MICHEL (GENERAL ET TECHNO.),privé sous contrat,51454,REIMS,51,MARNE,REIMS,44,...,NaN,NaN,NaN,3.0,18.0,19.0,NaN,1.0,4.0,17.0
2,2025,0530004S,LYCEE VICTOR HUGO,public,53062,CHATEAU GONTIER SUR MAYENNE,53,MAYENNE,NANTES,52,...,NaN,NaN,NaN,11.0,43.0,49.0,NaN,1.0,5.0,11.0
3,2025,0530010Y,LYCEE AMBROISE PARE,public,53130,LAVAL,53,MAYENNE,NANTES,52,...,NaN,NaN,2.0,21.0,58.0,81.0,NaN,NaN,7.0,23.0
4,2025,0530016E,LYCEE LAVOISIER,public,53147,MAYENNE,53,MAYENNE,NANTES,52,...,NaN,NaN,NaN,12.0,33.0,47.0,NaN,NaN,2.0,10.0

In [16]:
df_res.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32485 entries, 0 to 32484
Data columns (total 88 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   Année                                               32485 non-null  int64
 1   UAI                                                 32485 non-null  object
 2   Etablissement                                       32485 non-null  object
 3   Secteur                                             32485 non-null  object
 4   Code commune                                        32485 non-null  object
 5   Commune                                             32485 non-null  object
 6   Code departement                                    32485 non-null  object
 7   Département                                         32485 non-null  object
 8   Académie                                            32485 non-null  object
 9   Code région                                         32485 non-null  int64
 10  Region                                              32485 non-null  object
 11  Présents - Toutes séries                            32485 non-null  int64
 12  Taux de réussite - Toutes séries                    32485 non-null  float64
 13  Valeur ajoutée du taux de réussite - Toutes séries  32025 non-null  float64
 14  Taux d'accès 2nde-bac                               32324 non-null  float64
 15  Valeur ajoutée du taux d'acces 2nde-bac             31905 non-null  float64
 16  Taux de mentions - Toutes séries                    20890 non-null  float64
 17  Valeur ajoutée du taux de mentions - Toutes séries  20551 non-null  float64
 18  Présents - L                                        16111 non-null  float64
 19  Présents - ES                                       17813 non-null  float64
 20  Présents - S                                        18977 non-null  float64
 21  Présents - Gnle                                     10927 non-null  float64
 22  Présents - STI2D                                    7893 non-null   float64
 23  Présents - STD2A                                    1253 non-null   float64
 24  Présents - STMG                                     17615 non-null  float64
 25  Présents - STL                                      3757 non-null   float64
 26  Présents - ST2S                                     6341 non-null   float64
 27  Présents - S2TMD                                    335 non-null    float64
 28  Présents - STHR                                     929 non-null    float64
 29  Taux de réussite - L                                16111 non-null  float64
 30  Taux de réussite - ES                               17813 non-null  float64
 31  Taux de réussite - S                                18977 non-null  float64
 32  Taux de réussite - Gnle                             10927 non-null  float64
 33  Taux de réussite - STI2D                            7893 non-null   float64
 34  Taux de réussite - STD2A                            1253 non-null   float64
 35  Taux de réussite - STMG                             17615 non-null  float64
 36  Taux de réussite - STL                              3757 non-null   float64
 37  Taux de réussite - ST2S                             6341 non-null   float64
 38  Taux de réussite - S2TMD                            335 non-null    float64
 39  Taux de réussite - STHR                             929 non-null    float64
 40  Valeur ajoutée du taux de réussite - L              14937 non-null  float64
 41  Valeur ajoutée du taux de réussite - ES             17480 non-null  float64
 42  Valeur ajoutée du taux de réussite - S              18747 non-null  float64
 43  Valeur ajoutée du taux de réussite - Gnle           10747 non-null  float64
 44  Valeur ajoutée du taux de réussite - STI2D          7740 non-null   float64
 45  Valeur ajoutée du taux de réussite - STD2A          1220 non-null   float64
 46  Valeur ajoutée du taux de réussite - STMG           17291 non-null  float64
 47  Valeur ajoutée du taux de réussite - STL            3507 non-null   float64
 48  Valeur ajoutée du taux de réussite - ST2S           6225 non-null   float64
 49  Valeur ajoutée du taux de réussite - S2TMD          243 non-null    float64
 50  Valeur ajoutée du taux de réussite - STHR           848 non-null    float64
 51  Effectif de seconde                                 32415 non-null  float64
 52  Effectif de premiere                                32415 non-null  float64
 53  Effectif de terminale                               25523 non-null  float64
 54  Taux d'accès 1ere-bac                               32422 non-null  float64
 55  Taux d'accès terminale-bac                          25528 non-null  float64
 56  Valeur ajoutée du taux d'accès 1ere-bac             32005 non-null  float64
 57  Valeur ajoutée du taux d'accès terminale-bac        25158 non-null  float64
 58  Taux de mentions - L                                7211 non-null   float64
 59  Taux de mentions - ES                               8046 non-null   float64
 60  Taux de mentions - S                                8524 non-null   float64
 61  Taux de mentions - Gnle                             10927 non-null  float64
 62  Taux de mentions - STI2D                            5534 non-null   float64
 63  Taux de mentions - STD2A                            926 non-null    float64
 64  Taux de mentions - STMG                             11406 non-null  float64
 65  Taux de mentions - STL                              2542 non-null   float64
 66  Taux de mentions - ST2S                             4151 non-null   float64
 67  Taux de mentions - S2TMD                            220 non-null    float64
 68  Taux de mentions - STHR                             590 non-null    float64
 69  Valeur ajoutée du taux de mentions - L              6596 non-null   float64
 70  Valeur ajoutée du taux de mentions - ES             7914 non-null   float64
 71  Valeur ajoutée du taux de mentions - S              8439 non-null   float64
 72  Valeur ajoutée du taux de mentions - Gnle           10747 non-null  float64
 73  Valeur ajoutée du taux de mentions - STI2D          5422 non-null   float64
 74  Valeur ajoutée du taux de mentions - STD2A          894 non-null    float64
 75  Valeur ajoutée du taux de mentions - STMG           11173 non-null  float64
 76  Valeur ajoutée du taux de mentions - STL            2335 non-null   float64
 77  Valeur ajoutée du taux de mentions - ST2S           4048 non-null   float64
 78  Valeur ajoutée du taux de mentions - S2TMD          156 non-null    float64
 79  Valeur ajoutée du taux de mentions - STHR           515 non-null    float64
 80  Nombre de mentions TB avec félicitations - G        6597 non-null   float64
 81  Nombre de mentions TB sans félicitations - G        8593 non-null   float64
 82  Nombre de mentions B - G                            8747 non-null   float64
 83  Nombre de mentions AB - G                           8759 non-null   float64
 84  Nombre de mentions TB avec félicitations - T        570 non-null    float64
 85  Nombre de mentions TB sans félicitations - T        4658 non-null   float64
 86  Nombre de mentions B - T                            7124 non-null   float64
 87  Nombre de mentions AB - T                           7328 non-null   float64
dtypes: float64(76), int64(3), object(9)
memory usage: 21.8+ MB

In [17]:
df = pd.merge(df_ips, df_res, how='inner', on=["UAI"])

In [18]:
df.head()

,Rentrée scolaire,Académie_x,Code du département,Département_x,UAI,Nom de l'établissment,Code INSEE de la commune,Nom de la commune,Secteur_x,Type de lycée,...,Valeur ajoutée du taux de mentions - S2TMD,Valeur ajoutée du taux de mentions - STHR,Nombre de mentions TB avec félicitations - G,Nombre de mentions TB sans félicitations - G,Nombre de mentions B - G,Nombre de mentions AB - G,Nombre de mentions TB avec félicitations - T,Nombre de mentions TB sans félicitations - T,Nombre de mentions B - T,Nombre de mentions AB - T
0,2016-2017,LYON,1.0,AIN,0010010F,LYCEE GENERAL ET TECHNOLOGIQUE DU BUGEY,1034.0,BELLEY,public,LEGT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-2017,LYON,1.0,AIN,0010010F,LYCEE GENERAL ET TECHNOLOGIQUE DU BUGEY,1034.0,BELLEY,public,LEGT,...,NaN,NaN,2.0,15.0,25.0,44.0,NaN,1.0,4.0,20.0
2,2016-2017,LYON,1.0,AIN,0010010F,LYCEE GENERAL ET TECHNOLOGIQUE DU BUGEY,1034.0,BELLEY,public,LEGT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-2017,LYON,1.0,AIN,0010010F,LYCEE GENERAL ET TECHNOLOGIQUE DU BUGEY,1034.0,BELLEY,public,LEGT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-2017,LYON,1.0,AIN,0010010F,LYCEE GENERAL ET TECHNOLOGIQUE DU BUGEY,1034.0,BELLEY,public,LEGT,...,NaN,NaN,4.0,20.0,33.0,45.0,NaN,NaN,5.0,11.0

In [27]:
df.columns.to_list()

['Rentrée scolaire',
 'Académie_x',
 'Code du département',
 'Département_x',
 'UAI',
 "Nom de l'établissment",
 'Code INSEE de la commune',
 'Nom de la commune',
 'Secteur_x',
 'Type de lycée',
 'IPS voie GT',
 'IPS voie PRO',
 'IPS Ensemble GT-PRO',
 "Ecart-type de l'IPS voie GT",
 "Ecart-type de l'IPS voie PRO",
 'Année',
 'Etablissement',
 'Secteur_y',
 'Code commune',
 'Commune',
 'Code departement',
 'Département_y',
 'Académie_y',
 'Code région',
 'Region',
 'Présents - Toutes séries',
 'Taux de réussite - Toutes séries',
 'Valeur ajoutée du taux de réussite - Toutes séries',
 "Taux d'accès 2nde-bac",
 "Valeur ajoutée du taux d'acces 2nde-bac",
 'Taux de mentions - Toutes séries',
 'Valeur ajoutée du taux de mentions - Toutes séries',
 'Présents - L',
 'Présents - ES',
 'Présents - S',
 'Présents - Gnle',
 'Présents - STI2D',
 'Présents - STD2A',
 'Présents - STMG',
 'Présents - STL',
 'Présents - ST2S',
 'Présents - S2TMD',
 'Présents - STHR',
 'Taux de réussite - L',
 'Taux de réussite - ES',
 'Taux de réussite - S',
 'Taux de réussite - Gnle',
 'Taux de réussite - STI2D',
 'Taux de réussite - STD2A',
 'Taux de réussite - STMG',
 'Taux de réussite - STL',
 'Taux de réussite - ST2S',
 'Taux de réussite - S2TMD',
 'Taux de réussite - STHR',
 'Valeur ajoutée du taux de réussite - L',
 'Valeur ajoutée du taux de réussite - ES',
 'Valeur ajoutée du taux de réussite - S',
 'Valeur ajoutée du taux de réussite - Gnle',
 'Valeur ajoutée du taux de réussite - STI2D',
 'Valeur ajoutée du taux de réussite - STD2A',
 'Valeur ajoutée du taux de réussite - STMG',
 'Valeur ajoutée du taux de réussite - STL',
 'Valeur ajoutée du taux de réussite - ST2S',
 'Valeur ajoutée du taux de réussite - S2TMD',
 'Valeur ajoutée du taux de réussite - STHR',
 'Effectif de seconde',
 'Effectif de premiere',
 'Effectif de terminale',
 "Taux d'accès 1ere-bac",
 "Taux d'accès terminale-bac",
 "Valeur ajoutée du taux d'accès 1ere-bac",
 "Valeur ajoutée du taux d'accès terminale-bac",
 'Taux de mentions - L',
 'Taux de mentions - ES',
 'Taux de mentions - S',
 'Taux de mentions - Gnle',
 'Taux de mentions - STI2D',
 'Taux de mentions - STD2A',
 'Taux de mentions - STMG',
 'Taux de mentions - STL',
 'Taux de mentions - ST2S',
 'Taux de mentions - S2TMD',
 'Taux de mentions - STHR',
 'Valeur ajoutée du taux de mentions - L',
 'Valeur ajoutée du taux de mentions - ES',
 'Valeur ajoutée du taux de mentions - S',
 'Valeur ajoutée du taux de mentions - Gnle',
 'Valeur ajoutée du taux de mentions - STI2D',
 'Valeur ajoutée du taux de mentions - STD2A',
 'Valeur ajoutée du taux de mentions - STMG',
 'Valeur ajoutée du taux de mentions - STL',
 'Valeur ajoutée du taux de mentions - ST2S',
 'Valeur ajoutée du taux de mentions - S2TMD',
 'Valeur ajoutée du taux de mentions - STHR',
 'Nombre de mentions TB avec félicitations - G',
 'Nombre de mentions TB sans félicitations - G',
 'Nombre de mentions B - G',
 'Nombre de mentions AB - G',
 'Nombre de mentions TB avec félicitations - T',
 'Nombre de mentions TB sans félicitations - T',
 'Nombre de mentions B - T',
 'Nombre de mentions AB - T']